export const INDUSTRY_DETAILS = {
  'logistics-courier': {
    name: 'Logistics & Courier',
    slug: 'logistics-courier',
    tagline: 'End-to-end visibility for every shipment, every mile.',
    heroDesc: 'Timeline Telematics empowers logistics and courier companies with real-time fleet intelligence — reducing costs, improving delivery accuracy, and giving dispatchers complete operational control.',
    color: '#E8312A',
    stats: [
      { value: '28%', label: 'Average Fuel Savings' },
      { value: '99.4%', label: 'On-time Delivery Rate' },
      { value: '3x', label: 'Faster Dispute Resolution' },
      { value: '40%', label: 'Reduction in Idle Time' },
    ],
    challenges: [
      { title: 'Route Inefficiency', desc: 'Unoptimized routes lead to wasted fuel, late deliveries, and driver fatigue across large fleets.' },
      { title: 'Lack of Visibility', desc: 'Dispatchers have no real-time view of vehicle location, cargo status, or estimated arrival times.' },
      { title: 'Fuel Theft & Waste', desc: 'Unauthorized fuel consumption and poor driving habits silently erode margins on every route.' },
      { title: 'Proof of Delivery', desc: 'Manual delivery confirmation leads to disputes, chargebacks, and poor customer experience.' },
    ],
    solutions: [
      { title: 'Real-time GPS Tracking', desc: 'Live location of every vehicle on a single dashboard. Share ETAs with customers automatically.' },
      { title: 'AI Route Optimization', desc: 'Dynamic routing engine recalculates routes based on traffic, weather, and delivery priority.' },
      { title: 'Fuel Monitoring', desc: 'Detect fuel theft, excessive idling, and inefficient driving patterns with instant alerts.' },
      { title: 'Digital Proof of Delivery', desc: 'Capture e-signatures, photos, and timestamps at delivery — eliminate disputes instantly.' },
      { title: 'Driver Scorecard', desc: 'Score each driver on safety, efficiency, and compliance. Coach underperformers with data.' },
      { title: 'Automated Reporting', desc: 'Generate fleet performance, compliance, and cost reports with a single click.' },
    ],
    clients: ['TCS Pakistan', 'Leopards Courier', 'Call Courier', 'Aramex'],
  },

  'public-transport': {
    name: 'Public Transport',
    slug: 'public-transport',
    tagline: 'Reliable, safe, and efficient passenger transport at scale.',
    heroDesc: 'From city buses to school fleets, Timeline Telematics delivers the visibility and control transport operators need to run safe, punctual, and cost-effective services.',
    color: '#1d4ed8',
    stats: [
      { value: '22%', label: 'Improvement in Punctuality' },
      { value: '35%', label: 'Operational Cost Reduction' },
      { value: '100%', label: 'Passenger Safety Compliance' },
      { value: '60%', label: 'Fewer Breakdowns' },
    ],
    challenges: [
      { title: 'Schedule Adherence', desc: 'Buses running off-schedule frustrate passengers and damage the operator\'s reputation and revenue.' },
      { title: 'Passenger Safety', desc: 'Speeding, harsh braking, and fatigued drivers create serious safety risks for passengers.' },
      { title: 'Maintenance Costs', desc: 'Reactive maintenance leads to unexpected breakdowns, costly repairs, and service disruptions.' },
      { title: 'Route Performance', desc: 'No visibility into which routes are underperforming or where bottlenecks are occurring.' },
    ],
    solutions: [
      { title: 'Live Fleet Map', desc: 'See every bus on a real-time map. Identify delays before they impact passengers.' },
      { title: 'Passenger Safety Monitoring', desc: 'Speed alerts, harsh driving detection, and driver fatigue monitoring keep passengers protected.' },
      { title: 'Predictive Maintenance', desc: 'Engine diagnostics and service reminders prevent breakdowns and extend vehicle life.' },
      { title: 'Route Analytics', desc: 'Analyze route performance, peak load times, and schedule compliance across your entire network.' },
      { title: 'Driver Behavior Scoring', desc: 'Rank drivers by safety score. Reward top performers and coach those who need improvement.' },
      { title: 'Automated Compliance Reports', desc: 'Generate regulatory compliance reports automatically for transport authority submissions.' },
    ],
    clients: ['Emirates Transport', 'Daewoo Express', 'City Transport'],
  },

  'oil-gas': {
    name: 'Oil & Gas',
    slug: 'oil-gas',
    tagline: 'Uncompromising safety and efficiency for high-stakes operations.',
    heroDesc: 'In the oil and gas industry, operational failure is not an option. Timeline Telematics provides mission-critical fleet visibility, safety monitoring, and compliance tools for upstream, midstream, and downstream operations.',
    color: '#b45309',
    stats: [
      { value: '45%', label: 'Reduction in Safety Incidents' },
      { value: '30%', label: 'Fuel Cost Savings' },
      { value: '0', label: 'Compliance Violations' },
      { value: '24/7', label: 'Remote Asset Monitoring' },
    ],
    challenges: [
      { title: 'Remote Operations', desc: 'Vehicles and assets operating in remote fields are invisible to central command without telematics.' },
      { title: 'Safety & HSE Compliance', desc: 'Strict HSE requirements demand continuous monitoring of driver behavior and vehicle safety.' },
      { title: 'Fuel Management', desc: 'High fuel consumption in heavy field vehicles makes fuel monitoring critical to cost control.' },
      { title: 'Asset Utilization', desc: 'Expensive equipment sitting idle or being misused represents significant losses in capital investment.' },
    ],
    solutions: [
      { title: 'Remote Asset Tracking', desc: 'Track vehicles and equipment in the most remote locations using satellite-backed GPS technology.' },
      { title: 'HSE Compliance Monitoring', desc: 'Automated safety checklists, speed zone enforcement, and incident reporting for full HSE compliance.' },
      { title: 'Fuel Consumption Analytics', desc: 'Detailed fuel usage reports per vehicle and operator. Detect theft and waste immediately.' },
      { title: 'Geofence Alerts', desc: 'Define safe zones and restricted areas. Get instant alerts when vehicles leave authorized boundaries.' },
      { title: 'Heavy Asset Management', desc: 'Track drills, tankers, and specialized equipment. Monitor utilization and maintenance cycles.' },
      { title: 'Emergency SOS', desc: 'One-touch emergency alerts from drivers in the field, with instant dispatch notification.' },
    ],
    clients: ['PSO', 'Shell Pakistan', 'Attock Petroleum'],
  },

  'construction': {
    name: 'Construction',
    slug: 'construction',
    tagline: 'Keep your site moving and your equipment accounted for.',
    heroDesc: 'Construction fleets face unique challenges — equipment theft, idle time, and multi-site coordination. Timeline Telematics brings complete control to your construction operations.',
    color: '#b45309',
    stats: [
      { value: '50%', label: 'Reduction in Equipment Theft' },
      { value: '35%', label: 'Less Equipment Idle Time' },
      { value: '20%', label: 'Lower Maintenance Costs' },
      { value: '100%', label: 'Multi-site Visibility' },
    ],
    challenges: [
      { title: 'Equipment Theft', desc: 'Heavy machinery and vehicles left on unmonitored sites are frequent targets for theft.' },
      { title: 'Idle Time Waste', desc: 'Equipment running idle on site burns fuel and increases wear without adding productivity.' },
      { title: 'Multi-site Coordination', desc: 'Managing assets across multiple active construction sites creates blind spots and miscommunication.' },
      { title: 'Unauthorized Usage', desc: 'Vehicles and equipment used outside working hours or by unauthorized personnel drives up costs.' },
    ],
    solutions: [
      { title: 'Anti-theft Geofencing', desc: 'Set virtual boundaries around sites. Get instant alerts if any asset moves outside defined zones.' },
      { title: 'Equipment Utilization Reports', desc: 'See exactly how long each machine is active vs idle. Optimize deployment across sites.' },
      { title: 'Multi-site Dashboard', desc: 'Manage all active construction sites from a single screen — vehicles, equipment, and workforce.' },
      { title: 'Working Hours Enforcement', desc: 'Track engine on/off times and flag after-hours usage immediately.' },
      { title: 'Maintenance Scheduling', desc: 'Automatic service alerts based on engine hours prevent breakdowns during critical project phases.' },
      { title: 'Driver & Operator ID', desc: 'RFID-based driver identification ensures only authorized personnel operate your assets.' },
    ],
    clients: ['FWO', 'Descon Engineering', 'NLC'],
  },

  'healthcare': {
    name: 'Healthcare',
    slug: 'healthcare',
    tagline: 'On-time, every time — because delays cost lives.',
    heroDesc: 'Healthcare logistics demand absolute precision. Timeline Telematics ensures ambulances, medical supply vehicles, and patient transport fleets are always where they need to be.',
    color: '#0f766e',
    stats: [
      { value: '4 min', label: 'Faster Average Response Time' },
      { value: '100%', label: 'Cold Chain Integrity' },
      { value: '99.9%', label: 'Fleet Availability' },
      { value: '0', label: 'Missed Critical Deliveries' },
    ],
    challenges: [
      { title: 'Emergency Response Time', desc: 'Every minute counts in medical emergencies. Slow dispatch and routing delays cost lives.' },
      { title: 'Cold Chain Compliance', desc: 'Vaccines, blood, and pharmaceuticals require strict temperature control throughout transit.' },
      { title: 'Fleet Availability', desc: 'Unplanned vehicle breakdowns can leave medical facilities without critical supply deliveries.' },
      { title: 'Regulatory Compliance', desc: 'Healthcare transport is subject to strict government and international medical standards.' },
    ],
    solutions: [
      { title: 'Intelligent Dispatch', desc: 'Automatically route the nearest available vehicle to an emergency or delivery location.' },
      { title: 'Temperature Monitoring', desc: 'Real-time temperature sensors in medical vehicles alert staff to any cold chain breach immediately.' },
      { title: 'Predictive Maintenance', desc: 'Keep your fleet mission-ready with automated service alerts and diagnostics.' },
      { title: 'Patient Transport Tracking', desc: 'Give hospitals and families real-time visibility into patient transport vehicle location.' },
      { title: 'Compliance Documentation', desc: 'Automated logs for every trip — time, route, temperature, and driver — for full audit trails.' },
      { title: '24/7 Monitoring Center', desc: 'Round-the-clock fleet monitoring with escalation alerts for any deviation from protocol.' },
    ],
    clients: ['Shaukat Khanum', 'Agha Khan Hospital', 'Rescue 1122'],
  },

  'government': {
    name: 'Government',
    slug: 'government',
    tagline: 'Accountability, transparency, and efficiency in public sector fleets.',
    heroDesc: 'Government and public sector fleets operate under intense public scrutiny. Timeline Telematics delivers the transparency, accountability, and cost efficiency that public institutions demand.',
    color: '#1e40af',
    stats: [
      { value: '40%', label: 'Reduction in Vehicle Misuse' },
      { value: '25%', label: 'Fuel Budget Savings' },
      { value: '100%', label: 'Audit-ready Records' },
      { value: '3x', label: 'Improvement in Fleet Utilization' },
    ],
    challenges: [
      { title: 'Vehicle Misuse', desc: 'Government vehicles used for personal errands or outside duty hours result in significant wasted expenditure.' },
      { title: 'Lack of Accountability', desc: 'Without tracking, there is no way to verify where vehicles were, who drove them, or for how long.' },
      { title: 'Budget Overruns', desc: 'Unmonitored fuel consumption and maintenance costs lead to budget overruns year after year.' },
      { title: 'Audit Compliance', desc: 'Auditors require detailed fleet usage records that manual logbooks cannot reliably provide.' },
    ],
    solutions: [
      { title: 'Official Hours Geofencing', desc: 'Restrict vehicle usage to official routes and hours. Any deviation triggers an immediate alert.' },
      { title: 'Driver Accountability Logs', desc: 'Every trip automatically logged with driver ID, time, route, and distance — tamper-proof records.' },
      { title: 'Fuel Expense Tracking', desc: 'Match fuel card transactions to actual vehicle consumption. Identify discrepancies instantly.' },
      { title: 'Executive Dashboard', desc: 'Real-time fleet overview for department heads — utilization rates, costs, and compliance at a glance.' },
      { title: 'Automated Audit Reports', desc: 'One-click generation of detailed fleet usage reports ready for internal and external audits.' },
      { title: 'Ministry-wide Deployment', desc: 'Centralized platform to manage fleets across multiple departments and ministries from one system.' },
    ],
    clients: ['National Logistics Cell', 'NADRA', 'Punjab Government'],
  },

  'agriculture': {
    name: 'Agriculture',
    slug: 'agriculture',
    tagline: 'Smart fleet management from field to market.',
    heroDesc: 'Agricultural operations span vast distances and challenging terrain. Timeline Telematics helps agribusinesses track vehicles, protect assets, and optimize harvests with intelligent telematics.',
    color: '#15803d',
    stats: [
      { value: '30%', label: 'Reduction in Transport Costs' },
      { value: '100%', label: 'Crop Delivery Traceability' },
      { value: '50%', label: 'Less Equipment Downtime' },
      { value: '24/7', label: 'Remote Field Monitoring' },
    ],
    challenges: [
      { title: 'Vast Remote Areas', desc: 'Agricultural vehicles operate in areas with little connectivity, making tracking difficult.' },
      { title: 'Harvest Season Pressure', desc: 'During harvest, transport delays can lead to spoilage and significant financial losses.' },
      { title: 'Equipment Theft', desc: 'Tractors and agricultural machinery are high-value theft targets, especially in rural areas.' },
      { title: 'Fuel Costs', desc: 'Long distances and heavy machinery make fuel one of the largest expenses in agricultural operations.' },
    ],
    solutions: [
      { title: 'Satellite GPS Tracking', desc: 'Track vehicles and machinery even in the most remote fields using satellite-backed technology.' },
      { title: 'Harvest Logistics Optimization', desc: 'Coordinate transport from field to storage to market with real-time routing and scheduling.' },
      { title: 'Anti-theft Protection', desc: 'Immobilization capability and geofence alerts protect tractors and equipment around the clock.' },
      { title: 'Fuel Efficiency Monitoring', desc: 'Track consumption per field, per operator, and per machine to cut fuel waste significantly.' },
      { title: 'Equipment Health Monitoring', desc: 'Engine hour tracking and service alerts keep harvesters and tractors running through peak season.' },
      { title: 'Cold Chain for Perishables', desc: 'Temperature monitoring for refrigerated transport of fruits, vegetables, and dairy products.' },
    ],
    clients: ['Engro Foods', 'Fauji Fertilizer', 'Al-Shaheen Farms'],
  },
};